[package]
name = "autoflow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
arrow = "53.0.0"
nanoid = "0.4.0"
once_cell = "1.19.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.64"
tokio = "1.40.0"
