[package]
name = "node_adapter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { path = "../worker" }
js-sys = "0.3.76"
wasm-bindgen = { version = "0.2", features = ["std"] }
wasm-bindgen-futures = "0.4"
actix-utils = "3.0.1"
futures-core = { version = "0.3.31", default-features = false }
futures-util = { version = "0.3.31", default-features = false, features = ["std"] }
actix-service = "2.0.2"